set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# install packager after

set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'

TMUX_FZF_LAUNCH_KEY="C-f"

# must be the last line
run '~/.tmux/plugins/tpm/tpm'
